[workspace]
resolver = "3"
members = ["wayne-core", "wayne-protocol", "wayne-macros"]

[workspace.dependencies]
wayne-core = { path = "wayne-core" }
wayne-macros = { path = "wayne-macros" }
wayne-protocol = { path = "wayne-protocol" }
