[workspace]
resolver = "3"
members = ["wayne-core", "wayne-protocol", "wayne-protocol-macros"]

[workspace.dependencies]
wayne-core = { path = "wayne-core" }
wayne-protocol = { path = "wayne-protocol" }
wayne-protocol-macros = { path = "wayne-protocol-macros" }
