[package]
name = "wayne-core"
version = "0.1.0"
edition = "2024"

[dependencies]
bon = "3.3.2"
derive_more = { version = "2.0.1", features = ["display"] }
fs2 = "0.4.3"
log = "0.4.26"
thiserror = "2.0.12"

[dev-dependencies]
anyhow = "1.0.95"
