[package]
name = "wayne-core"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "the core foundation structures for wayne"
repository = "https://github.com/rhedgeco/wayne"
readme = "README.md"

[dependencies]
bon = "3.3.2"
derive_more = { version = "2.0.1", features = ["display"] }
log = "0.4.26"
thiserror = "2.0.12"
rustix = { version = "1.0.1", features = ["net", "fs"] }

[dev-dependencies]
anyhow = "1.0.95"
constcat = "0.6.0"
