[package]
name = "wayne-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", features = ["display"] }
fixed = "1.29"
thiserror = "2.0"
wayne-protocol-macros.workspace = true
