[package]
name = "wayne-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
derivative = "2.2"
derive_more = { version = "2.0", features = ["display"] }
fixed = "1.29"
thiserror = "2.0"
wayne-macros.workspace = true
log = "0.4"
